type = "fleetrl_2.jobs.environment_creation_job.EnvironmentCreationJob"
[EnvironmentCreationJob]
_environement_dataset_job = ""
_reward_function_job = ""

# recommended, improves performance by adding redundant information to the observation space
use_auxiliary_data = true

normalization_strategy = "NONE" # NONE or ORACLE todo explain
model_frequency = '15min'

[EnvironmentCreationJob.episode]
episode_length = 24 # in hours
end_cutoff_days = 60 # todo describe
price_lookahead = 8 # in hours, maximum 12
building_load_lookahead = 4 # in hours
pv_production_lookahead = 4 # in hours

[EnvironmentCreationJob.misc]
battery_degradation_type = "NONLINEAR" # NONE, NONLINEAR, EMPIRICAL
time_picker = 'RANDOM'  # STATIC, RANDOM, EVAL
real_time = false  # use model frequency data or feed input data as it comes
