type = "fleetrl_2.jobs.ev_config_job.EvConfigJob"

[EvConfigJob.battery]
battery_capacity = 60.0 # in kWh
initial_state_of_health = 1.0
on_board_charger_max_power = 100.0 # in kW
charging_efficiency = 0.91
discharging_efficiency = 0.91
default_soc = 0.5 # todo
target_soc = 0.85 # SoC to reach when EV leaves

[EvConfigJob.auxiliary]
ambient_temperature = 25.0 # in °C
min_laxity = 2 # todo

# todo - what is the ideal battery size, that gives the best penalty magnitude for good training loss?
#max_batt_cap_in_all_use_cases = ?
