type = "fleetrl_2.jobs.reward_function_job.RewardFunctionJob"

[RewardFunctionJob]
price_multiplier = 3.33
price_exponent = 1

[RewardFunctionJob.reward]
fully_charged = 1

[RewardFunctionJob.penalty]
invalid_action = -0.2
overcharging = -0.0055
overloading_multiplier = 1
clip_overcharging = -0.2

[RewardFunctionJob.ignore]
invalid_action = false
overcharging = false
overloading = false
price = false
